### PR TITLE
chore(docs): split Read examples in README to separate sections

### PR DESCRIPTION
**Pull request by akj2018**
## Description
Edited README.md to create separate code blocks for Read Relationship Tuples example.

## References

[OpenFGA RFC](https://github.com/openfga/rfcs)
[Contributing to OpenFGA](https://github.com/openfga/.github/blob/main/CONTRIBUTING.md)

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Review by rhamzeh — CHANGES_REQUESTED** [review]
Thanks @akj2018 

You probably need to duplicate this part across all the code blocks:

```py
response = await api_instance.read(body)
# response = ReadResponse({"tuples": [Tuple({"key": TupleKey({"user":"...","relation":"...","object":"..."}), "timestamp": datetime.fromisoformat("...") })]})
```

**Comment by rhamzeh** [comment]
Also, looking at it now, the three above code blocks should read:
> `body = ReadRequest(...)`
instead of
> `body = TupleKey(...)`

Mind doing that change too?

**Comment by akj2018** [comment]
Hi @rhamzeh, thanks for letting me know. I have made the required changes in my latest commit.

**Review by rhamzeh — APPROVED** [review]
Thanks @akj2018 !

**Pull request merged**
