### PR TITLE
chore(docs): clean up and fix imports and initialization in README

### PR DESCRIPTION
**Pull request by JRudransh**
## Description

Changes are based on `openfga-sdk==0.4.0`

1. Wherever we are using some modules from the `openfga_sdk` I have imported them and keep them as comments.
2. I found some syntax errors in existing code, so i fixed them
3. I have reformatted the code
4. I have added return statement on main function from there we are doing some query 

## References

https://github.com/openfga/python-sdk/issues/28

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Review by JRudransh — COMMENTED** [review]
Everything seems good

**Comment by JRudransh** [comment]
This PR Also covers #23, I was not aware that we have different Issue for that

**Review by rhamzeh — APPROVED** [review]

**Comment by rhamzeh** [comment]
Thanks for your PR @JRudransh!

Can I ask you to:
- Sign the EasyCLA in the comment above (we need it in order to merge)
- amend your commit message to be `chore(docs): clean up and fix imports and initialization in README` and force push?

**Review by rhamzeh — CHANGES_REQUESTED** [review]
Thanks for your PR @JRudransh!

Can I ask you to:
- Sign the EasyCLA in the comment above (we need it in order to merge)
- amend your commit message to be `chore(docs): clean up and fix imports and initialization in README` and force push?

Marking as "Request Changes" so that we don't merge before EasyCLA is signed

**Comment by JRudransh** [comment]
I have already signed the EasyCLA, I have also got the conformation email
image

**Review by JRudransh — COMMENTED** [review]
I have added required changes

**Review by rhamzeh — APPROVED** [review]
Thank you!

**Pull request merged**
